### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by afior1981** [acando14/motor-project-meetup#4]
Your requirements could not be resolved to an installable set of packages.

alex@alex:~/symfony/motor-project-meetup$  composer require --dev doctrine/doctrine-fixtures-bundle
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Using version ^3.4 for doctrine/doctrine-fixtures-bundle
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-fixtures-bundle ^3.4 -> satisfiable by doctrine/doctrine-fixtures-bundle[3.4.0].
    - Conclusion: remove doctrine/persistence 1.3.6
    - Conclusion: don't install doctrine/persistence 1.3.6
    - doctrine/doctrine-fixtures-bundle 3.4.0 requires doctrine/persistence ^1.3.7|^2.0 -> satisfiable by doctrine/persistence[1.3.7, 1.3.8, 2.0.0, 2.0.1, 2.1.0].
    - Can only install one of: doctrine/persistence[1.3.7, 1.3.6].
    - Can only install one of: doctrine/persistence[1.3.8, 1.3.6].
    - Can only install one of: doctrine/persistence[2.0.0, 1.3.6].
    - Can only install one of: doctrine/persistence[2.0.1, 1.3.6].
    - Can only install one of: doctrine/persistence[2.1.0, 1.3.6].
    - Installation request for doctrine/persistence (locked at 1.3.6) -> satisfiable by doctrine/persistence[1.3.6].

Installation failed, reverting ./composer.json to its original content.

**Comment by ghost** [comment]
Risolto!
