### ISSUE TITLE
Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_template", "em", "factories", "migrations", "migrations_paths", "organize_migrations", "services", "storage".

### ISSUE THREAD

**Issue by afior1981** [acando14/motor-project-meetup#5]
Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_template", "em", "factories", "migrations", "migrations_paths", "organize_migrations", "services", "storage".
ExceptionStack Trace
Symfony\Component\Config\Definition\Exception\
InvalidConfigurationException
in /home/alex/symfony/motor-project-meetup/vendor/symfony/config/Definition/ArrayNode.php (line 326)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/config/Definition/BaseNode.php -> normalizeValue (line 412)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/config/Definition/Processor.php -> normalize (line 34)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/config/Definition/Processor.php -> process (line 50)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/dependency-injection/Extension/Extension.php -> processConfiguration (line 111)
in /home/alex/symfony/motor-project-meetup/vendor/doctrine/doctrine-migrations-bundle/DependencyInjection/DoctrineMigrationsExtension.php -> processConfiguration (line 39)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php -> load (line 76)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php -> process (line 39)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/dependency-injection/Compiler/Compiler.php -> process (line 91)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/dependency-injection/ContainerBuilder.php -> compile (line 736)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/http-kernel/Kernel.php -> compile (line 541)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/http-kernel/Kernel.php -> initializeContainer (line 780)
in /home/alex/symfony/motor-project-meetup/vendor/symfony/http-kernel/Kernel.php -> preBoot (line 183)
Kernel->handle()
in /home/alex/symfony/motor-project-meetup/public/index.php (line 25)
    Request::setTrustedHosts([$trustedHosts]);}$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);$request = Request::createFromGlobals();$response = $kernel->handle($request);$response->send();$kernel->terminate($request, $response);
require('/home/alex/symfony/motor-project-meetup/public/index.php')
in /home/alex/.symfony/php/5baafc7556af60d29cef27e32c5e4a78b7ad7449-router.php (line 29)

**Comment by ghost** [comment]
Risolto!
